version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    filters:
      branches:
      only:
        - master
    steps:
      - checkout
      - run: python3 main.py

workflows:
  build:
    jobs:
      - build
